### PR TITLE
Updating to fastjet 3.3.0

### PR DESCRIPTION
**Pull request by rappoccio**
Here is the "bare" import of fastjet 3.3.0. As usual, I will go through and make this a thread-safe version next in a different branch, but this is the unmodified version.

### CODE REVIEW

**Comment by rappoccio** [comment]
I also have the CMS-specific patches ready but I need a cms/v3.3.0 branch to make a PR into:

https://github.com/rappoccio/fastjet/tree/cms/v3.3.0

**Comment by smuzaffar** [comment]
@rappoccio , cms/v3.3.0 branch is now available https://github.com/cms-externals/fastjet/tree/cms/v3.3.0

**Comment by smuzaffar** [comment]
Once we have the cms patch for thread safety in cms/v3.3.0 then we will update cms-sw/cmsdist to include it.

**Comment by rappoccio** [comment]
Somehow this isn't working. Github won't let me make a PR. It says "cms-externals:cms/v3.3.0 and rappoccio:cms/v3.3.0 are entirely different commit histories." Sorry, my git-fu is insufficiently powerful to figure out what to do ;)

**Comment by rappoccio** [comment]
I think we have to explicitly pull the branch I have on my fork into the master.

**Comment by rappoccio** [comment]
Wait... never mind. I will just reapply the patches to the 3.3.0 branch you made.

**Comment by rappoccio** [comment]
Fixed now: https://github.com/cms-externals/fastjet/pull/15

**Pull request closed without merging**
