### PR TITLE
Moving fastjet threading PR to cms/v3.1.0

### PR DESCRIPTION
**Pull request by rappoccio**
Correction of https://github.com/cms-externals/fastjet/pull/7

### CODE REVIEW

**Comment by nclopezo** [comment]
Results are ready: 
Tested at: c115647ecf6b47c3d7eca5f94583f78025449f2d
https://cmssdt.cern.ch/SDT/jenkins-artifacts/cms-externals-pr-integration/22

**Comment by ktf** [comment]
@nclopezo can you re base this on top of cms/v3.1.0? We can then discuss in
ORP if we want to go forward with this.

**Comment by nclopezo** [comment]
The commits that you want on top of cms/v3.1.0 are 605269a, fee3397,  db1dce9, a7d41cf, c115647 ?

**Comment by nclopezo** [comment]
or also the ones that come from https://github.com/cms-externals/fastjet/commits/cms/v3.0.3 ?

**Comment by ktf** [comment]
We want everything but the merge commits.

**Comment by nclopezo** [comment]
I rebased it here: https://github.com/cms-externals/fastjet/pull/9

**Comment by smuzaffar** [comment]
same as #11

**Pull request closed without merging**
