### PR TITLE
Rebase Moving fastjet threading PR 8

### PR DESCRIPTION
**Pull request by nclopezo**
I rebased https://github.com/cms-externals/fastjet/pull/8 on top of cms/v3.1.0 

I had conflicts when applying 61f7c3e and 93978bc. I would like to confirm that this is correct. @rappoccio, @Dr15Jones, @ktf

### CODE REVIEW

**Comment by ktf** [comment]
What were the conflicts and how did you solve them?

**Comment by nclopezo** [comment]
Hi,

For 605269a there were conflicts in:

 include/fastjet/Error.hh 

```
<<<<<<< HEAD
  static bool _print_errors;           ///< do we print anything?
  static bool _print_backtrace;        ///< do we print the backtrace?
  static std::ostream * _default_ostr; ///< the output stream (cerr if not set)
#if (!defined(FASTJET_HAVE_EXECINFO_H)) || defined(__FJCORE__)
  static LimitedWarning _execinfo_undefined;
#endif
=======

  // CMS change: the following are no longer class statics
  //  moved to file static since they were changed to std::atomic
  //  and we still need to allow this header to be parsed by
  //  non C++11 compilers.
  // Change not endorsed by fastjet collaboration 
  //static bool _print_errors;           ///< do we print anything?
  //static bool _print_backtrace;        ///< do we print the backtrace?
  //static std::ostream* _default_ostr; ///< the output stream (cerr if not set)
>>>>>>> 605269a... Attempting to restart CMS-specific merge of fastjet

Left what is in 605269a... Attempting to restart CMS-specific merge of fastjet"

```

For fee3397 there were conflicts in:

src/ClusterSequence.cc

```

<<<<<<< HEAD
bool ClusterSequence::_first_time = true;
LimitedWarning ClusterSequence::_exclusive_warnings;
=======

//CMS change: use std::atomic for thread safety.
//   Change not endorsed by fastjet collaboration
#if __cplusplus >= 201103L
static std::atomic<bool> _first_time{true};
static std::atomic<int> _n_exclusive_warnings{0};
#else
static bool _first_time =true;
static int _n_exclusive_warnings =0;
#endif
LimitedWarning ClusterSequence::_exclusive_warnings(0);
LimitedWarning ClusterSequence::_changed_strategy_warning(0);
>>>>>>> fee3397... Removing some duplicated variables that were introduced in merge

left fee3397... Removing some duplicated variables that were introduced in merge

```

src/Error.cc

```
<<<<<<< HEAD
=======

void Error::set_print_errors(bool print_errors) {_print_errors = print_errors;}

void Error::set_default_stream(std::ostream * ostr) {
    _default_ostr = ostr;
}

>>>>>>> fee3397... Removing some duplicated variables that were introduced in merge
FASTJET_END_NAMESPACE

left fee3397... Removing some duplicated variables that were introduced in merge
```

**Comment by nclopezo** [comment]
But it seems that it is wrong:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/cms-externals-pr-integration/24

**Comment by rappoccio** [comment]
I'm a little confused. I thought I based my PR on top of cms/v3.1.0 originally. Maybe I made a mistake, but this seems to me that I did it right : 

https://github.com/nclopezo/fastjet/commits/93978bc70aa0dbe5c599a88f8f5154f957072436/src/ClusterSequence.cc

Was there something I did wrong here? 

Also, what are the action items for me now? Did you solve these or should I?

**Comment by nclopezo** [comment]
@rappoccio 

Hi Salvatore,
In your PR https://github.com/cms-externals/fastjet/pull/8 you have commits that are already in the branch cms/v3.1.0 https://github.com/cms-externals/fastjet/commits/cms/v3.1.0

If you see the commits of that branch you will see for example this one bf270f2b0931efa127f6ced3ec17fb7e86faa544 in the original branch, in your PR you have this one https://github.com/rappoccio/fastjet/commit/fe68d452c6839dcf9d8f8a2691bfd414cd071295
Which does the same changes but has a different hash,  that should have happened when you rebased it. 

I tried to do the rebase myself, to include only the changes that you want to merge. But I found some conflicts and I was not able to resolve them correctly. I would prefer if you could resolve them. Your pull request should be the branch cms/v3.1.0 + your changes

You can try do the following after cloning the repository:

<pre>
git remote add rappoccio git@github.com:rappoccio/fastjet.git
git checkout cms/v3.1.0
git checkout -b new-branch
for each of your commits:
  git cherry-pick "commit"
  "resolve conflicts"
git push rappoccio new-branch
</pre>

At the end new-branch should have the history of cms/v3.1.0 + what you want to change, and you can create a pull request.

**Comment by rappoccio** [comment]
I'm really confused about this, actually. What I did was : 
- start with cms/v3.1.0
- merge ALL of the changes from cms/v3.0.3 (cms specific patches)
- did my changes
- committed and made my PR

For my information, what was wrong with that? 

If I start with cms/v3.1.0, and just cherry pick all of my checkouts, then this doesn't give me the same thing I started from, it's not compiling at the very least. 

So do I have to do this all over again? I'm totally lost here.

**Comment by nclopezo** [comment]
What I see that should not bee in https://github.com/cms-externals/fastjet/pull/8 are the first 6 commits:

 Applies fastjet-3.0.3-nobanner 2ba8069
 Apply fastjet-3.0.1-sicone-banner  938dd12
 Apply fastjet-3.0.1-noemptyareawarning.patch   5bd6f3f
 Apply fastjet-3.0.1-nodegeneracywarning.patch  472c594
 Applies fastjet-3.0.1-cluster-sequence-banner.patch    0729647
 Applies fastjet-3.0.1-silence-warnings.patch.   fe68d45

Because those changes are already in the branch cms/v3.1.0 https://github.com/cms-externals/fastjet/commits/cms/v3.1.0

**Comment by rappoccio** [comment]
OK, so merging was the wrong thing to do here? 

And now this means I have to basically start it all from scratch again? It's not coming back to where it started from, this is confusing to me because I think these are all doing the same thing in a slightly different order, but git should be able to handle that, no?

**Comment by nclopezo** [comment]
The difference is that the hashes are different, so git treats them as different commits.

**Comment by rappoccio** [comment]
Thanks for the explanation. I'll try to get this working via the cherry-picks, but it's not trivial, it isn't giving the same content. It will take me a bit.

**Comment by rappoccio** [comment]
OK, I'm not completely that the cherry pick is doing what we want. I tried with the above method, and it does not pick out all of the changes that we want, since it ignores all of the changes in 3.0.3 from @Dr15Jones that dealt with mulitthreading that I merged into my branch. So basically this would mean I would have to apply that somehow anyway, but I'm not sure how to do that besides simply redoing the edits by hand.

On the other hand, I did : 

git clone https://github.com/cms-externals/fastjet.git
cd fastjet
git checkout cms/v3.1.0
git remote add mine git@github.com:rappoccio/fastjet.git
git fetch mine
git checkout -b merge-attempt
git merge remotes/mine/cms/v3.1.0
git checkout -b rappoccio/v3.1.0-rebase
git push mine rappoccio/v3.1.0-rebase

And it gives exactly what we want. I'm not sure what the problem is that you're having. Can we just take whatever is there and call that the "cms/v3.1.0" branch? This is really holding up 73x so we need this in ASAP. 

Here is the branch on my git area : 

https://github.com/rappoccio/fastjet/tree/rappoccio/v3.1.0-rebase

**Comment by nclopezo** [comment]
Hi Salvatore,
I created a PR with your branch: https://github.com/cms-externals/fastjet/pull/10

**Comment by rappoccio** [comment]
Thanks for all the help David! If this works, then I think we're good to go. 

Cheers,
Sal

**Comment by smuzaffar** [comment]
Already done in #11

**Pull request closed without merging**
