### PR TITLE
Rappoccio/v3.1.0 rebase

### PR DESCRIPTION
**Pull request by nclopezo**

### CODE REVIEW

**Comment by nclopezo** [comment]
@rappoccio 
Hi Salvatore,
Sorry, it seems that there are compilation errors. See the previous comment. You can push to your branch rappoccio/v3.1.0-rebase and this PR should be updated.

**Comment by rappoccio** [comment]
Hmmm, it works for me on lxbuild041. What are your settings? I did : 

setenv CXXFLAGS "-O3 -Wall -ffast-math -std=c++0x -msse3 -ftree-vectorize"
./configure --enable-shared --enable-atlascone --enable-cmsiterativecone --enable-siscone --prefix=/build/srappocc/fastjet_install

Interestingly the c++0x doesn't work on my Mac OS X Yosemite build.

**Comment by rappoccio** [comment]
Any news here? I cannot reproduce the problem (except on mac os x).

**Comment by smuzaffar** [comment]
A new Pull Request was created by @nclopezo (David Mendez) for branch cms/v3.1.0.

Rappoccio/v3.1.0 rebase

You can sign-off by replying to this message having '+1' in the first line of your reply.
You can reject by replying  to this message having '-1' in the first line of your reply.

external issue cms-sw/cmsdist#1748

**Comment by ghost** [comment]
@rappoccio @davidlange6 Seems like this PR fell into oblivion... Do we still need it? If that is the case a rebase is necessary (perhaps we already merged the necessary commit through another PR?).

**Comment by rappoccio** [comment]
I thought @nclopezo @ktf  actually put this in separately in a different PR at the time :+1: 

https://github.com/cms-externals/fastjet/commit/b22035e7b44afb596fce6d393139b59b8bb00d47

**Comment by smuzaffar** [comment]
included in #11

**Pull request closed without merging**
