### PR TITLE
Updating CMS mirror of fastjet SVN head to fastjet 3.1.0

### PR DESCRIPTION
**Pull request by rappoccio**
Fastjet 3.1.0 contains speed improvements from 20-200%. Here is the alignment to the HEAD of their SVN.

### CODE REVIEW

**Comment by ktf** [comment]
@degano can you test this out as is? Rebuilding fastjet.spec should be enough for now. I'm asking because I suspect we will need changes if we want to switch from using tar balls to using SVN. BTW, @rappoccio how did you create this commit? Simply `git add -a`? Did you take care of eventually removed files?

**Comment by ghost** [comment]
@ktf ok, I'll test it now.

**Comment by ghost** [comment]
Built on top of 7_3_X/stable branch taking the code from rappoccio/fastjet master branch.
Compilation looks fine out of the box.

**Comment by rappoccio** [comment]
Hi, All,

I just copied the files from the 3.1.0 tarball into the directory and added everything (before configuration). 

Cheers,
Sal

**Comment by ktf** [comment]
Then I'm afraid we have a bit of a mixup.. :-/ I'll try to import the 
3.1.0 tar ball and see if there is any difference.

**Comment by rappoccio** [comment]
OK, for future reference what was I supposed to have done?

**Comment by ktf** [comment]
I just created a a cms/v3.1.0 branch and added there a few of the trivial patches we have. @Dr15Jones multithreading fixes, however, still do not seem to be there and do not merge anymore. We should discuss how to proceed.

**Comment by rappoccio** [comment]
I put in a PR for the threading patches.

**Comment by rappoccio** [comment]
This can be closed.

**Pull request closed without merging**
